dataset:
  dataset_root: raw_data/CleanedJiang
  diff_max_len: 110
  msg_max_len: 30
  encoder_name_or_path: microsoft/codebert-base
  decoder_name_or_path: microsoft/codebert-base
  train_dataloader_conf:
    batch_size: 8
    shuffle: true
    num_workers: 4
  val_dataloader_conf:
    batch_size: 8
    num_workers: 4
  test_dataloader_conf:
    batch_size: 8
    num_workers: 4
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: codebert+codebert use diff with changes only
  project: commit_message_generation
model:
  learning_rate: 1e-4
  encoder_name_or_path: microsoft/codebert-base
  decoder_name_or_path: microsoft/codebert-base
  unfreeze_after: 10
  freeze_after: -1
  num_layers_encoder: -1
  num_layers_decoder: -1
trainer:
  gpus: 1
  max_epochs: 40
  num_sanity_val_steps: 2
  accumulate_grad_batches: 1